### ISSUE TITLE
Windows paths are broken

### ISSUE THREAD

**Issue by 1IxI1** [1IxI1/blueprint-scaffold#9]
![telegram-cloud-photo-size-2-5474603098212259793-x](https://github.com/1IxI1/blueprint-scaffold/assets/53380262/84d223d5-8971-45f8-ad86-ad7262a162af)
![telegram-cloud-photo-size-2-5474429036072655700-x](https://github.com/1IxI1/blueprint-scaffold/assets/53380262/23387c82-5018-422f-bfa2-97759e08ef93)

**Comment by 1IxI1** [comment]
https://github.com/the-real-some-dao/a-careers-smc

**Comment by ZirionNeft** [comment]
Same problem. In WSL also not working

Upd: found how to fix. Will make a PR tomorrow

**Comment by 1IxI1** [comment]
Fixed with #15
